### ISSUE TITLE
"TimeoutError: Registering on SIP Server timed out" causes unknown state, hangs process

### ISSUE THREAD

**Issue by f3ndot** [tayler6000/pyVoIP#125]
Hi there. Using pyVoIP v1.6.4. I have a pretty simple program that works. However after a undetermined amount of time, I occasionally get this exception:

```py
Exception in thread SIP Register CSeq: 225:
Traceback (most recent call last):
  File "/Users/justin/.pyenv/versions/3.10.4/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/justin/.pyenv/versions/3.10.4/lib/python3.10/threading.py", line 1371, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/justin/Library/Caches/pypoetry/virtualenvs/voip-project-l2C45DWo-py3.10/lib/python3.10/site-packages/pyVoIP/SIP.py", line 1707, in register
    raise TimeoutError("Registering on SIP Server timed out")
TimeoutError: Registering on SIP Server timed out
```

And, when I do, the following occurs:

* `VoIPPhone.get_status()` still returns `PhoneStatus.REGISTERED`
* The VoIP server I'm connected (www.VoIP.ms) to does not say a client is registered
* My main sleep loop continues to run
* If I Ctrl+C/Keyboard Interrupt to cause my code to call `VoIPPhone.stop()`, it hangs forever. A few subsequent interrupts finally exits to console[1]

Here is my minimal code:

```python3
import structlog
import time
from pyVoIP.VoIP import VoIPPhone, VoIPCall

logger = structlog.stdlib.get_logger(__name__)

def answer(call: VoIPCall):
    logger.info("Someone is ringing! Doing nothing...")


def run_phone():
    phone = VoIPPhone(
        server="xxxxxxxx.voip.ms",
        port=5060,
        username="xxxxxxxx",
        password="xxxxxxxx",
        callCallback=answer,
        myIP="xxx.xxx.xxx.xxx",
    )
    logger.info(f"Starting up phone.", status=str(phone.get_status()))
    phone.start()
    logger.info(f"Connected and online!", status=str(phone.get_status()))
    try:
        while True:
            # The exception appears to generate here at some point
            logger.info(str(phone.get_status()), status=str(phone.get_status()))
            time.sleep(60)
    except KeyboardInterrupt:
        logger.info(f"Shutting down!", status=str(phone.get_status()))
        phone.stop()  # Hangs here forever after Ctrl+C/Keyboard interrupt
        logger.info(f"Done!", status=str(phone.get_status()))
```

Is there a way for me to recover from this with an `except TimeoutError`? Is this a bug in the software? Let me know 😄 

<details>
<summary>[1]: See second traceback on subsequent Ctrl+C's</summary>

```
^C2023-04-16 18:17:06 [info     ] Shutting down!
^CTraceback (most recent call last):
  File "/Users/justin/Code/voip-project/voip_project/voip.py", line 164, in run_phone
    time.sleep(60)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/justin/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/justin/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/justin/Code/voip-project/voip_project/__main__.py", line 12, in <module>
    run_phone()
  File "/Users/justin/Code/voip-project/voip_project/voip.py", line 167, in run_phone
    phone.stop()
  File "/Users/justin/Library/Caches/pypoetry/virtualenvs/voip-project-l2C45DWo-py3.10/lib/python3.10/site-packages/pyVoIP/VoIP.py", line 672, in stop
    self.sip.stop()
  File "/Users/justin/Library/Caches/pypoetry/virtualenvs/voip-project-l2C45DWo-py3.10/lib/python3.10/site-packages/pyVoIP/SIP.py", line 959, in stop
    self.deregister()
  File "/Users/justin/Library/Caches/pypoetry/virtualenvs/voip-project-l2C45DWo-py3.10/lib/python3.10/site-packages/pyVoIP/SIP.py", line 1641, in deregister
    self.recvLock.acquire()
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/Users/justin/.pyenv/versions/3.10.4/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/Users/justin/.pyenv/versions/3.10.4/lib/python3.10/threading.py", line 1560, in _shutdown
    lock.acquire()
KeyboardInterrupt:

$
```
</details>

**Comment by tayler6000** [comment]
Thank you for the extremely detailed issue @f3ndot! It is extremely helpful.

It looks like I forgot a `recvLock.release()` somewhere.  Ideally, we would self-recover from a timeout, but that is currently not implemented.  This should be an easy enough fix for this that I'll probably put out a v1.6.5

**Comment by the-master-student** [comment]
Hi @tayler6000,

I have a similar problem, even though I installed the latest version. A snippet of code:

```
def _initPhone(self):
        """ Method to initialize phone object"""
        """ Check if phone was already instantiated"""
        if self._phone is not None:
            self._phone.stop()
            self._phone = None

        try:
            self._logger.debug("Initializing new phone object")
            self._updateCurrentSipPort()
            self._phone = VoIPPhone(self._voiceServingConfiguration.serverIp, self._voiceServingConfiguration.serverPort,
                                    self._voiceServingConfiguration.username, self._voiceServingConfiguration.password,
                                    callCallback=self._answerRecord, myIP=self._voiceServingConfiguration.myIp,
                                    sipPort=self._sipPort)
            self._phone.start()
            self._logger.debug("Awaiting call")
        except Exception:
            self._logger.exception("Unexpected exception during phone init.")
```
After approx. 30 second, I land in the exception part. Any hints how I can debug this? My asterisk server is running. Thank you in advance.

**Comment by tayler6000** [comment]
> After approx. 30 second, I land in the exception part. Any hints how I can debug this? My asterisk server is running. Thank you in advance.

So you're saying you're making it to the logger line saying unexpected exception?  If so, then you're experiencing a different issue.  I would make sure your asterisk is configured for UDP. Let me know if you still have issues.

**Comment by the-master-student** [comment]
Hi,

first thank you so much for your swift response. The server has been configured correctly and is functioning seamlessly when using the Linphone app. I recently removed my exception, which has led to the following error:

```
  File "/VoiceServing/VoIPReceiver.py", line 188, in _initPhone
    self._phone.start()
  File "/usr/local/lib/python3.9/dist-packages/pyVoIP/VoIP.py", line 668, in start
    self.sip.start()
  File "/usr/local/lib/python3.9/dist-packages/pyVoIP/SIP.py", line 949, in start
    self.register()
  File "/usr/local/lib/python3.9/dist-packages/pyVoIP/SIP.py", line 1707, in register
    raise TimeoutError("Registering on SIP Server timed out")
TimeoutError: Registering on SIP Server timed out
```

Your assistance is highly appreciated. Thank you so much.

**Comment by f3ndot** [comment]
@tayler6000 looks like you may have fixed this bug with https://github.com/tayler6000/pyVoIP/commit/733fc7f7100f143b6c141c8c7903dca7392a5a8c (it has a `self.recvLock.release()`). My code has been running for a few hours with no timeout issue.
