### ISSUE TITLE
AttributeError: 'VoIPSocket' object has no attribute 'recv'

### ISSUE THREAD

**Issue by VadyChel** [tayler6000/pyVoIP#152]
I tried to create call, but throw this error. I use development version

```
2023-06-22 10:35:23,295 | ERROR    | uvicorn.error:123 - Traceback (most recent call last):
  File "D:\venv\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\src\app.py", line 14, in lifespan
    await api.ws.start()
  File "D:\src\websocket_manager.py", line 31, in start
    await self.on_message(message=msg.data)
  File "D:\src\websocket_manager.py", line 57, in on_message
    self._events[event_type](data)
  File "D:\src\api.py", line 63, in call_create
    call_id = self.call(data["phone"])
  File "D:\src\api.py", line 76, in call
    created_call = self.voip.call(number=phone)
  File "D:\venv\lib\site-packages\pyVoIP\VoIP\phone.py", line 333, in call
    request, call_id, sess_id = self.sip.invite(
  File "D:\venv\lib\site-packages\pyVoIP\SIP\client.py", line 817, in invite
    response = SIPMessage(self.s.recv(8192))
AttributeError: 'VoIPSocket' object has no attribute 'recv'
```

**Comment by tayler6000** [comment]
pyVoIP 2.0 is unstable, please use pyVoIP 1.6.5rc1 for the latest stable.

**Comment by VadyChel** [comment]
> pyVoIP 2.0 is unstable, please use pyVoIP 1.6.5rc1 for the latest stable.

pyVoIP 1.6.5rc1 support OPTIONS?

**Comment by VadyChel** [comment]
> pyVoIP 2.0 is unstable, please use pyVoIP 1.6.5rc1 for the latest stable.

pyVoIP.SIP.SIPParseError: Unable to decipher SIP request: OPTIONS [uri];transport=UDP SIP/2.0

It's with pyVoIP 1.6.5rc1

**Comment by VadyChel** [comment]
And pyVoIP 1.6.5rc1 not support DIGEST auth
