### ISSUE TITLE
Help to use this library

### ISSUE THREAD

**Issue by mika-nt28** [tayler6000/pyVoIP#158]
Hi,

When used the exemple on documentation I have this error
```py
Exception in thread SIP Register CSeq: 27:
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 1266, in run
self.function(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/dist-packages/pyVoIP/SIP.py", line 1729, in register
response = SIPMessage(resp)
File "/usr/local/lib/python3.9/dist-packages/pyVoIP/SIP.py", line 345, in __init__
self.parse(data)
File "/usr/local/lib/python3.9/dist-packages/pyVoIP/SIP.py", line 384, in parse
raise SIPParseError(
pyVoIP.SIP.SIPParseError: Unable to decipher SIP request: NOTIFY sip:6005@192.168.0.100:5062;transport=UDP SIP/2.0
```

I'm connect to Asterisk 16.28.0~dfsg-0+deb11u3 built by nobody @ buildd.debian.org on a unknown running Linux on 2023-06-22 12:47:22 UTC

Can you help me to resolve my problem

**Comment by DopeforHope** [comment]
Same for me.

**Comment by kevinyang330** [comment]
> Same for me.  我也是一样。
Solved this problem?
