### ISSUE TITLE
pyVoIP.SIP.SIPParseError: Unable to decipher SIP request: OPTIONS 

### ISSUE THREAD

**Issue by addyuchiha** [tayler6000/pyVoIP#187]
I am trying to connect my voip provider ad make calls but I am getting this error

Code:
```py
from pyVoIP.VoIP import VoIPPhone, InvalidStateError

def answer(call): # This will be your callback function for when you receive a phone call.
    try:
        call.answer()
        call.hangup()
    except InvalidStateError:
        pass

if __name__ == "__main__":
    phone=VoIPPhone('sip.plusnet.de', 5060, 'fo342155ipxxxxxx', 'f0xxxxx',  sipPort=5060, rtpPortLow=10000, rtpPortHigh=20000)
    phone.start()

    while 1==1:
        i = input()
        if i=="a":
            phone.start()
        if i=="s":
            print(phone.get_status())
        if i=="d":
            phone.call(input())
        if i=="f":
            phone.stop()
```

```py
> PhoneStatus.REGISTERED
> s
> 00918840101948
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> TODO: Add 500 Error on Receiving SIP Response
> Traceback (most recent call last):
>   File "/home/addy/Desktop/x/x.py", line 19, in <module>
>     phone.call(input())
>   File "/home/addy/.local/lib/python3.10/site-packages/pyVoIP/VoIP/VoIP.py", line 690, in call
>     request, call_id, sess_id = self.sip.invite(
>   File "/home/addy/.local/lib/python3.10/site-packages/pyVoIP/SIP.py", line 1611, in invite
>     response = SIPMessage(self.s.recv(8192))
>   File "/home/addy/.local/lib/python3.10/site-packages/pyVoIP/SIP.py", line 347, in __init__
>     self.parse(data)
>   File "/home/addy/.local/lib/python3.10/site-packages/pyVoIP/SIP.py", line 386, in parse
>     raise SIPParseError(
> pyVoIP.SIP.SIPParseError: Unable to decipher SIP request: OPTIONS sip:fo342155ipxxxxxxxx@[2409:4089:ac02:b76e:c0:0:200:0]:5060;transport=UDP SIP/2.0

```

**Comment by tayler6000** [comment]
This has been resolved in 2.0
