### ISSUE TITLE
key error while registration

### ISSUE THREAD

**Issue by BRIDGE-AI** [tayler6000/pyVoIP#222]
@tayler6000 

Please can you check this out one more?
I'm testing the first example code again using 2.0.0a4 which has been fixed #217.

# code

same on https://github.com/tayler6000/pyVoIP/issues/217#issuecomment-1894991298

# logs

```
$ python t_ex1_ann.py
SENT:
REGISTER sip:211.233.26.247:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK7aae94666ac44439b36c26b83'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>', 'tag': '', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS', 'NOTIFY']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0a4
Expires: 120
Content-Length: 0

Body:

Raw:
b'REGISTER sip:211.233.26.247:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK7aae94666ac44439b36c26b83\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, NOTIFY\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0a4\r\nExpires: 120\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 401 Unauthorized

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK7aae94666ac44439b36c26b83', 'received': '43.202.127.199'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c', 'tag': 'ebcb6c0114297d73a48fab2b598eb87c', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
WWW-Authenticate: {'header': 'WWW-Authenticate', 'method': 'Digest', 'realm': 'sip1.1stnet.co.kr', 'nonce': '6be5f220592a70d7f6bb463470a9509c', 'stale': 'true', 'algorithm': 'MD5'}
Content-Length: 0

Body:

Raw:
b'SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK7aae94666ac44439b36c26b83;received=43.202.127.199\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nWWW-Authenticate: Digest realm="sip1.1stnet.co.kr", nonce="6be5f220592a70d7f6bb463470a9509c", stale=true, algorithm=MD5\r\nContent-Length: 0\r\n\r\n'
New Connection Started
Deregistering <pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217d5b0>
self.conns=[<pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217d5b0>]
listening: [["6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060", "13ced07b", "ebcb6c0114297d73a48fab2b598eb87c", 0]]

msgs: []


REGISTERATION ERROR: 'uri'
New register thread
Press enter to disable the phoneSENT:
REGISTER sip:211.233.26.247:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK26ebdf0d171f4696831ada27d'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>', 'tag': '', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 4e07408562bedb8b60ce05c1decfe3ad@0.0.0.0:5060
CSeq: {'check': 3, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS', 'NOTIFY']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0a4
Expires: 120
Content-Length: 0

Body:

Raw:
b'REGISTER sip:211.233.26.247:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK26ebdf0d171f4696831ada27d\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>\r\nCall-ID: 4e07408562bedb8b60ce05c1decfe3ad@0.0.0.0:5060\r\nCSeq: 3 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, NOTIFY\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0a4\r\nExpires: 120\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 401 Unauthorized

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK26ebdf0d171f4696831ada27d', 'received': '43.202.127.199'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c', 'tag': 'ebcb6c0114297d73a48fab2b598eb87c', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 4e07408562bedb8b60ce05c1decfe3ad@0.0.0.0:5060
CSeq: {'check': 3, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
WWW-Authenticate: {'header': 'WWW-Authenticate', 'method': 'Digest', 'realm': 'sip1.1stnet.co.kr', 'nonce': '6be5f220592a70d7f6bb463470a9509c', 'stale': 'true', 'algorithm': 'MD5'}
Content-Length: 0

Body:

Raw:
b'SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK26ebdf0d171f4696831ada27d;received=43.202.127.199\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c\r\nCall-ID: 4e07408562bedb8b60ce05c1decfe3ad@0.0.0.0:5060\r\nCSeq: 3 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nWWW-Authenticate: Digest realm="sip1.1stnet.co.kr", nonce="6be5f220592a70d7f6bb463470a9509c", stale=true, algorithm=MD5\r\nContent-Length: 0\r\n\r\n'
New Connection Started
Deregistering <pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217dd30>
self.conns=[None, <pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217dd30>]
listening: [["4e07408562bedb8b60ce05c1decfe3ad@0.0.0.0:5060", "13ced07b", "ebcb6c0114297d73a48fab2b598eb87c", 1]]

msgs: []


REGISTERATION ERROR: 'uri'
New register thread
SENT:
REGISTER sip:211.233.26.247:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bKe959b77df4834f679ac4ca415'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>', 'tag': '', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: ef2d127de37b942baad06145e54b0c61@0.0.0.0:5060
CSeq: {'check': 5, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS', 'NOTIFY']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0a4
Expires: 120
Content-Length: 0

Body:

Raw:
b'REGISTER sip:211.233.26.247:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bKe959b77df4834f679ac4ca415\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>\r\nCall-ID: ef2d127de37b942baad06145e54b0c61@0.0.0.0:5060\r\nCSeq: 5 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, NOTIFY\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0a4\r\nExpires: 120\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 401 Unauthorized

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bKe959b77df4834f679ac4ca415', 'received': '43.202.127.199'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c', 'tag': 'ebcb6c0114297d73a48fab2b598eb87c', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: ef2d127de37b942baad06145e54b0c61@0.0.0.0:5060
CSeq: {'check': 5, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
WWW-Authenticate: {'header': 'WWW-Authenticate', 'method': 'Digest', 'realm': 'sip1.1stnet.co.kr', 'nonce': '6be5f220592a70d7f6bb463470a9509c', 'stale': 'true', 'algorithm': 'MD5'}
Content-Length: 0

Body:

Raw:
b'SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bKe959b77df4834f679ac4ca415;received=43.202.127.199\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c\r\nCall-ID: ef2d127de37b942baad06145e54b0c61@0.0.0.0:5060\r\nCSeq: 5 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nWWW-Authenticate: Digest realm="sip1.1stnet.co.kr", nonce="6be5f220592a70d7f6bb463470a9509c", stale=true, algorithm=MD5\r\nContent-Length: 0\r\n\r\n'
New Connection Started
Deregistering <pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217dbe0>
self.conns=[None, None, <pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217dbe0>]
listening: [["ef2d127de37b942baad06145e54b0c61@0.0.0.0:5060", "13ced07b", "ebcb6c0114297d73a48fab2b598eb87c", 2]]

msgs: []


REGISTERATION ERROR: 'uri'
SENT:
REGISTER sip:211.233.26.247:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK88903302b31749739182edc62'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>', 'tag': '', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 7902699be42c8a8e46fbbb4501726517@0.0.0.0:5060
CSeq: {'check': 7, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS', 'NOTIFY']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0a4
Expires: 0
Content-Length: 0

Body:

Raw:
b'REGISTER sip:211.233.26.247:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK88903302b31749739182edc62\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>\r\nCall-ID: 7902699be42c8a8e46fbbb4501726517@0.0.0.0:5060\r\nCSeq: 7 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, NOTIFY\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0a4\r\nExpires: 0\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 401 Unauthorized

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK88903302b31749739182edc62', 'received': '43.202.127.199'}]
From: {'raw': '"07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b', 'tag': '13ced07b', 'uri': 'sip:07076830783@0.0.0.0:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '0.0.0.0', 'port': 5060}
To: {'raw': '"07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c', 'tag': 'ebcb6c0114297d73a48fab2b598eb87c', 'uri': 'sip:07076830783@211.233.26.247:5060', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '07076830783', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 7902699be42c8a8e46fbbb4501726517@0.0.0.0:5060
CSeq: {'check': 7, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
WWW-Authenticate: {'header': 'WWW-Authenticate', 'method': 'Digest', 'realm': 'sip1.1stnet.co.kr', 'nonce': '6be5f220592a70d7f6bb463470a9509c', 'stale': 'true', 'algorithm': 'MD5'}
Content-Length: 0

Body:

Raw:
b'SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK88903302b31749739182edc62;received=43.202.127.199\r\nFrom: "07076830783" <sip:07076830783@0.0.0.0:5060>;tag=13ced07b\r\nTo: "07076830783" <sip:07076830783@211.233.26.247:5060>;tag=ebcb6c0114297d73a48fab2b598eb87c\r\nCall-ID: 7902699be42c8a8e46fbbb4501726517@0.0.0.0:5060\r\nCSeq: 7 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:93D867DF-178D-4D1A-9D63-BD3FC2F0AC98>"\r\nWWW-Authenticate: Digest realm="sip1.1stnet.co.kr", nonce="6be5f220592a70d7f6bb463470a9509c", stale=true, algorithm=MD5\r\nContent-Length: 0\r\n\r\n'
New Connection Started
Deregistering <pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217da60>
self.conns=[None, None, None, <pyVoIP.networking.sock.VoIPConnection object at 0x7fb81217da60>]
listening: [["7902699be42c8a8e46fbbb4501726517@0.0.0.0:5060", "13ced07b", "ebcb6c0114297d73a48fab2b598eb87c", 3]]

msgs: []


DEREGISTERATION ERROR: 'uri'
Error unpacking data, only using header: not enough values to unpack (expected 2, got 1)
DEREGISTERATION ERROR: [Errno 9] Bad file descriptor
Exception in thread SIP Register CSeq: 5:
Traceback (most recent call last):
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 1291, in register
    registered = self.__register()
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 1341, in __register
    password_request = self.gen_register(response)
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 647, in gen_register
    regRequest += self.gen_authorization(request)
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 497, in gen_authorization
    + f'uri="{digest["uri"]}",response="{digest["digest"]}",'
KeyError: 'uri'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 1312, in register
    self.fatal_callback()
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/VoIP/phone.py", line 313, in fatal
    self.stop(failed=True)
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/VoIP/phone.py", line 306, in stop
    self.sip.stop()
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 239, in stop
    self.deregister()
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 1210, in deregister
    deregistered = self.__deregister()
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 1232, in __deregister
    conn = self.send(first_request)
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/SIP/client.py", line 250, in send
    return self.s.send(request.encode("utf8"))
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/networking/sock.py", line 476, in send
    conn.send(data)
  File "/home/ec2-user/bridge/duplex-client/src/pyVoIP/pyVoIP/networking/sock.py", line 68, in send
    self.sock.s.sendto(data, addr)
OSError: [Errno 9] Bad file descriptor
```

Thank you.

**Comment by tayler6000** [comment]
@BRIDGE-AI The latest version of development has this fixed. Please let me know if you have any more issues.
