### ISSUE TITLE
SIPClient object has no attribute 'out'

### ISSUE THREAD

**Issue by TecDroiD** [tayler6000/pyVoIP#277]
Hi, haven't been around with VoIP for some time and just wanted to try the current state of the project..
.. so i wrote a little test program:
```
from pyVoIP.VoIP import VoIPPhone, InvalidStateError
import wave
import sys

if __name__ == "__main__":
    phone = VoIPPhone("local.server", 5060, "xxx", "yyy")
    call = phone.call("01xxxxxx")
    try:
        while call.state == CallState.DIALING:
            pass

        if call.state != CallState.ANSWERED:
            sys.exit(0)

        f = wave.open('announcment.wav', 'rb')
        frames = f.getnframes()
        data = f.readframes(frames)
        f.close()

        call.write_audio(data)

        stop = time.time() + (frames / 8000)

        while time.time() <= stop and call.state == CallState.ANSWERED:
            time.sleep(0.1)
        call.hangup()
    except InvalidStateError:
        print("Invalid State" + call.state)
    except:
        call.hangup()
```
which results in this traceback:
`
Traceback (most recent call last):
  File "/home/tecdroid/projects/pyvoip/call.py", line 7, in <module>
    call = phone.call("01xxxxx")
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tecdroid/projects/pyvoip/env/lib/python3.11/site-packages/pyVoIP/VoIP/VoIP.py", line 688, in call
    request, call_id, sess_id = self.sip.invite(
                                ^^^^^^^^^^^^^^^^
  File "/home/tecdroid/projects/pyvoip/env/lib/python3.11/site-packages/pyVoIP/SIP.py", line 1610, in invite
    self.out.sendto(invite.encode("utf8"), (self.server, self.port))
    ^^^^^^^^
AttributeError: 'SIPClient' object has no attribute 'out'
`
am I doin'g anything wrong here?

**Comment by TecDroiD** [comment]
can be closed.. out must be injected by phone.start() which i forgot.. but still. my FritzBox does not do a call..
