### ISSUE TITLE
Help with identifying issues relating to client connection

### ISSUE THREAD

**Issue by premudeshi** [tayler6000/pyVoIP#45]
Hello. 

I am trying to connect this with my FreePBX stack however I am having issues with the call being picked up at all. I am on a Mac, running python3 in a virtual environment. My FreePBX is hosted remotely on the cloud. 

I am trying to use the basic demo code, but the call doesn't get answered, and instead I get a 503 error, as if the client doesn't connect to the VoIP server. I receive no error when I run the code, and the connection seems to go through as if I put an incorrect password, it gives me an error. 

I was wondering how I could debug my connection and Identify where the issue is. 
Thanks.

**Comment by xyc0815** [comment]
Maybe you can use my Fork for a test with a cloud based installation. https://github.com/xyc0815/pyVoIP/tree/v1.6.0.1-dev . The different is, that a proxy is possible,  more debugging and on some parts IPv6 support. It would be good to attach the debug output.

**Comment by premudeshi** [comment]
How can I utilize the proxy? When using the simple hangup code, I get an error (without defining proxy) 
```
Traceback (most recent call last):
  File "<blah>/test.py", line 19, in <module>
    phone = VoIPPhone(serverip, serverport, serverusername, serverpass, callCallback=answer, myIP='<my local ip>')
  File "<blah>/pyVoIP/VoIP.py", line 398, in __init__
    self.sip = SIP.SIPClient(server, port, username, password,
TypeError: __init__() got an unexpected keyword argument 'proxy'
```

**Comment by xyc0815** [comment]
Proxy can be None, when you don't have a proxy in between.

**Comment by tayler6000** [comment]
> https://github.com/xyc0815/pyVoIP/tree/v1.6.0.1-dev

I could be wrong, but based off your stack trace it doesn't look like you're using this branch specifically. tayler6000/pyVoIP is not capable of using proxies yet.  I intend to implement this in 2.0.0.  However, the branch linked above is capable of using SIP Proxies.  You will need to use that.

**Comment by premudeshi** [comment]
My initial issues stems from the tayler6000/pyVoIP master branch, but I haven't had any better luck with the tayler6000/pyVoIP dev branch either. Like I said, the code runs, it doesn't spit out any errors, but it won't accept calls.

That being said, I was messing around with the demo code and it seems to make calls. It just won't receive them. 

> the branch linked above is capable of using SIP Proxies. You will need to use that.

Conceptually, why would I need to use a SIP Proxy? Can I not connect to an Asterisk sever on the cloud without needing a proxy? Would I have to setup the proxy on the local network?

**Comment by tayler6000** [comment]
Apologies, I thought you were specifically trying to use a proxy.  It could be an issue with private vs public IP addresses.  I would have to see your configuration to be sure.  @xyc0815 I saw your fork had some preliminary public/private IP support, do you have any thoughts on this?

**Comment by xyc0815** [comment]
If I don't made an error the proxy is optional in my fork, when you set the proxy with None the proxy is not used. Some online SIP services must connected by a proxy service. Because I use an online SIP server (with a proxy) in my branch I've public/private IP support, so that the pyVoIP can be used behind a NAT service.

**Comment by tayler6000** [comment]
> in my branch I've public/private IP support, so that the pyVoIP can be used behind a NAT service.

Can you post a code snippet here on how to use that feature in your fork?

**Comment by xyc0815** [comment]
This was not so simple. First I added in the class SIPClient in __init__ the variables self.my_public_ip = None and self.my_public_port = None.

I also added this two functions to the SIPClient:
```
    def get_my_ip(self) -> str:
        return self.my_public_ip if self.my_public_ip else self.myIP

    def get_my_port(self) -> str:
        return self.my_public_port if self.my_public_port else self.myPort
```
In the methode register I added a part to get the used public IP / port from the first response and write them to self.my_public_ip and self.my_public_port. 
```
        if len(response.headers['Via']) > 0 and 'received' in response.headers['Via'][0] \
                and 'rport' in response.headers['Via'][0]:
            self.my_public_ip = response.headers['Via'][0]['received']
            self.my_public_port = response.headers['Via'][0]['rport']
            debug(f"{self.__class__.__name__}.{inspect.stack()[0][3]} after received Message register 1"
                  f" received {self.my_public_ip} rport {self.my_public_port}")
```
The difficult part was to find out, where to set this informations in the messages creations. Here is the example from def gen_subscribe(self, response: SIPMessage) -> str:
```
        subRequest += 'Contact: ' + \
                      f'<sip:{self.username}@{self.get_my_ip()}:{self.get_my_port()};' + \
                      'transport=UDP>;+sip.instance=' + \
                      f'"<urn:uuid:{self.urnUUID}>"\r\n'
```
When you search for self.get_my_id in SIPClient you will find every part where I changed this.
I hope I don't forget something.

**Comment by premudeshi** [comment]
For the tayler6000/pyVoIP repo, do I need to accessible through the WAN? Can I use an instance of ngrok to test it out? If so, what would be the code to use domains instead of IPs?

**Comment by tayler6000** [comment]
For the tayler6000 repo the server I communicate with is within my NAT and that server calls out.  For me, I'm using Asterisk.  You can try setting your pyVoIP server to your DMZ and turn on your router's SIP Application Layer Gateway.

**Comment by premudeshi** [comment]
I tried running an instance on my local network (Asterisk running on 192.168.x.xxx) and running the basic hangup script on my laptop (192.168.x.yyy) and every time I call the number, my softphone returns with error 503. My laptops firewall is off and the extension used in the code works. 

What am I doing wrong?

**Comment by xyc0815** [comment]
Is it possible that you add the log output for a better overview?

**Comment by premudeshi** [comment]
I am using Asterisk, which log file output should I share?

**Comment by premudeshi** [comment]
So I got good news! I was able to get the code to pick up and end the call, by changing the Quality Frequency to 0 on FreePBX. I am guessing this has something to do with #46 as going through the SIP log it seems there is a lot less OPTION calls. 

However I now get this when running the first example on the tyler6000 master repo. 
`sys:1: UserWarning: RTP Payload type G726-32 not found.`

**Comment by data1456** [comment]
How do you get that?I have similar question with you.

**Comment by tayler6000** [comment]
> However I now get this when running the first example on the tayler6000 master repo. `sys:1: UserWarning: RTP Payload type G726-32 not found.`
> 
> Edit: It seems like this doesn't hinder the actual code. However I would like to know the fix if possible.

This is most likely due to the fact that the codec `G726-32` is not defined at https://github.com/tayler6000/pyVoIP/blob/master/pyVoIP/RTP.py#L47 which after a quick Google search makes sense as it is a dynamic codec not defined in the RFC.  If you disable that codec option on your PBX it should stop the issue.
