### ISSUE TITLE
KeyError: 'd4735e3a265e16eee03f59718b9b5d03@0.0.0.0:5060'

### ISSUE THREAD

**Issue by iccor56** [tayler6000/pyVoIP#85]
running this code i get an unhandled error of "KeyError: 'd4735e3a265e16eee03f59718b9b5d03@0.0.0.0:5060'"
`My_VoIPhone.test success
Traceback (most recent call last):
  File "C:\Users\dstaudt\Documents\Python\CIS_VOIP.py", line 31, in <module>
    phone.start()
  File "C:\Users\dstaudt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyVoIP\VoIP.py", line 656, in start
    self.sip.start()
  File "C:\Users\dstaudt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyVoIP\SIP.py", line 946, in start
    self.register()
  File "C:\Users\dstaudt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyVoIP\SIP.py", line 1762, in register
    self.parseMessage(response)
  File "C:\Users\dstaudt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyVoIP\SIP.py", line 876, in parseMessage
    return self.parse_message(message)
  File "C:\Users\dstaudt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyVoIP\SIP.py", line 885, in parse_message
    self.callCallback(message)
  File "C:\Users\dstaudt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyVoIP\VoIP.py", line 529, in callback
    self._callback_RESP_NotFound(request)
  File "C:\Users\dstaudt\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyVoIP\VoIP.py", line 619, in _callback_RESP_NotFound
    self.calls[call_id].notFound(request)
KeyError: 'd4735e3a265e16eee03f59718b9b5d03@0.0.0.0:5060'
`

`class My_VoIPhone(VoIPPhone):
	def test(self):
		print("My_VoIPhone.test success")

	def simple_answer(call): # This will be your callback function for when you receive a phone call.
		try:
			call.answer()
			call.hangup()
		except InvalidStateError:
			pass

if __name__ == "__main__":
	#print("CCM ping test", flush=True)
	from pythonping import ping
	ping_response = ping('192.168.1.5',timeout=1,count=2)

	if(ping_response.rtt_avg_ms<100):
		pass
		#print("CCM ping pass", flush=True)
	else:
		pass
		#print("CCM ping fail", flush=True)
		sys.exit("Error: Ping to CCM Failed")

	#phone = My_VoIPhone(server="192.168.1.5", port=5060, username="test8", password="0008")
	phone = My_VoIPhone(server="192.168.1.5", port=5060, username="Python01", password="Python", callCallback=My_VoIPhone.simple_answer)
	phone.test()
	phone.start()
	input('Press enter to disable the phone')
	phone.stop()
`

am i missing a variable?? the ping works fine. i set up the user name and password so those are correct.

**Comment by iccor56** [comment]
the same user name and password work just fine for a physical polycom phone. 

and of course libraries should not crash.

**Comment by Hokid** [comment]
Try to use domain name of your PBX/VoIP server instead of IP. For example:
```
phone = My_VoIPhone(server="mypbxserver.com", port=5060, username="Python01", password="Python", callCallback=My_VoIPhone.simple_answer)
```

I had the same issue and that helped me.

**Comment by iccor56** [comment]
there is none. it is on a closed network. testing environment. no internet
access

**Comment by tayler6000** [comment]
In that case, you can just use your server's computer name, if your network is set up correctly, that should resolve.  Worst case you can configure your hosts file.

**Comment by iccor56** [comment]
And why does the library crash?

**Comment by iccor56** [comment]
Alsoi don't know the computer name. It's a virtual machine our IT dept set
up
